# Note that only one of these targets is required
# setup IAM roles: https://docs.getdbt.com/docs/profile-bigquery#section-required-permissions

jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth # for production runs: https://docs.getdbt.com/docs/profile-bigquery#section-service-account-file-authentication
      project: wam-bam-258119
      dataset: dbt_bq_example # You can also use "schema" here
      threads: 4 # https://docs.getdbt.com/docs/configure-your-profile#section-understanding-threads
      timeout_seconds: 300
      location: US # Optional, one of US or EU
      priority: interactive # interactive or batch
  config:
    send_anonymous_usage_stats: False
