version: 2

sources:
  - name: dbt_bq_example
    database: "{{ env_var('PROJECT_ID', 'dbt-project-346515') }}" 
    schema: dbt_demo

    freshness:
      warn_after: { count: 2010, period: day } # 1 day old from time you run the source snapshot command
      error_after: { count: 2095, period: day } # 2 days old from time you run the source snapshot command

    loaded_at_field: order_date

    tables:
      - name: raw_customers
        freshness: null # no freshness tests
      - name: raw_orders
      - name: raw_payments
        freshness: null # no freshness tests

exposures:
  - name: customer_orders
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: >
      our customer orders
    
    depends_on:
      - ref('customer_orders')
      - source('dbt_bq_example', 'raw_orders')
      
    owner:
      name: Francis from Data
      email: francis@mightycanary.com

  - name: customers
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/2
    description: >
      our customer list
    
    depends_on:
      - ref('stg_customers')
      - source('dbt_bq_example', 'raw_customers')
      
    owner:
      name: Francis from Data
      email: francis@mightycanary.com
