name: Build and Deploy dbt docs static website to Cloud Run

on:
  push:
    branches: [master, feature-github-actions]
  pull_request:
    branches: [master]

env:
  #TODO(developer): update PROJECT_ID, REGION, IMAGE
  PROJECT_ID: "wam-bam-258119"
  REGION: "us-central1"
  IMAGE: "dbt-docs-cloud-run"
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./service_account.json

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}
          project_id: "wam-bam-258119" #TODO: fix later to be env var

      # - name: dbt docs generate
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - run: pip3 install -r ./requirements.txt
      - run: dbt --version
      - run: 'echo "$KEYFILE" > ./service_account.json' # persist file in root dir
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}} # add a github secret(https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository)
      - run: dbt debug
      # - run: dbt docs generate

      # Build and push image to Google Container Registry
      # Reference: https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml
      # gcloud builds submit CLI is NOT used as it does not persist dbt docs generation run beforehand
      - name: Build
        run: |-
          dbt docs generate &&
          docker build . --tag gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA &&
          gcloud auth configure-docker &&
          docker push gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA

      # Deploy image to Cloud Run based on branch name
      - name: Deploy
        run: |-
          gcloud run deploy "$IMAGE-${GITHUB_REF##*/}" \
            --quiet \
            --region "$REGION" \
            --image "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
