name: Cloud Run Website

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  #TODO(developer): update PROJECT_ID, REGION, IMAGE
  PROJECT_ID: "wam-bam-258119"
  REGION: "us-central1"
  IMAGE: "dbt-docs-cloud-run"
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./service_account.json

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "296.0.0"
          service_account_key: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}

      # Setup dbt configs
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - run: pip3 install -r ./requirements.txt
      - run: dbt --version
      - run: 'echo "$KEYFILE" > ./service_account.json' # persist file in root dir
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}} # add a github secret
      - run: dbt debug --target service_account_runs

      # Build and push image to Google Container Registry
      # gcloud builds submit CLI is NOT used as it does not persist dbt docs generation run beforehand
      - name: Build and push to Google Container Registry
        run: |-
          dbt docs generate --target service_account_runs &&
          docker build . --tag gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA &&
          gcloud auth configure-docker --quiet &&
          docker push gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA

      # Deploy image to Cloud Run based on branch name
      - name: Deploy-Live URL can be found HERE
        run: |-
          gcloud run deploy "$IMAGE-${GITHUB_REF##*/}" \
            --quiet \
            --project "$PROJECT_ID" \
            --region "$REGION" \
            --image "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
